//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirArqui.webArticulo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="webArticulo.ServiceArquiSoap")]
    public interface ServiceArquiSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idArticulo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar", ReplyAction="*")]
        ConsumirArqui.webArticulo.InsertarResponse Insertar(ConsumirArqui.webArticulo.InsertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirArqui.webArticulo.InsertarResponse> InsertarAsync(ConsumirArqui.webArticulo.InsertarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idArticulo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificar", ReplyAction="*")]
        ConsumirArqui.webArticulo.ModificarResponse Modificar(ConsumirArqui.webArticulo.ModificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificar", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirArqui.webArticulo.ModificarResponse> ModificarAsync(ConsumirArqui.webArticulo.ModificarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idArticulo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        ConsumirArqui.webArticulo.EliminarResponse Eliminar(ConsumirArqui.webArticulo.EliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirArqui.webArticulo.EliminarResponse> EliminarAsync(ConsumirArqui.webArticulo.EliminarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insertar", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirArqui.webArticulo.InsertarRequestBody Body;
        
        public InsertarRequest() {
        }
        
        public InsertarRequest(ConsumirArqui.webArticulo.InsertarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idArticulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string precio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string costo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cantidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string material;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string categoria;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string descripcion;
        
        public InsertarRequestBody() {
        }
        
        public InsertarRequestBody(string idArticulo, string nombre, string precio, string costo, string cantidad, string material, string categoria, string descripcion) {
            this.idArticulo = idArticulo;
            this.nombre = nombre;
            this.precio = precio;
            this.costo = costo;
            this.cantidad = cantidad;
            this.material = material;
            this.categoria = categoria;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirArqui.webArticulo.InsertarResponseBody Body;
        
        public InsertarResponse() {
        }
        
        public InsertarResponse(ConsumirArqui.webArticulo.InsertarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarResult;
        
        public InsertarResponseBody() {
        }
        
        public InsertarResponseBody(string InsertarResult) {
            this.InsertarResult = InsertarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Modificar", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirArqui.webArticulo.ModificarRequestBody Body;
        
        public ModificarRequest() {
        }
        
        public ModificarRequest(ConsumirArqui.webArticulo.ModificarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idArticulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string precio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string costo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cantidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string material;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string categoria;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string descripcion;
        
        public ModificarRequestBody() {
        }
        
        public ModificarRequestBody(string idArticulo, string nombre, string precio, string costo, string cantidad, string material, string categoria, string descripcion) {
            this.idArticulo = idArticulo;
            this.nombre = nombre;
            this.precio = precio;
            this.costo = costo;
            this.cantidad = cantidad;
            this.material = material;
            this.categoria = categoria;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirArqui.webArticulo.ModificarResponseBody Body;
        
        public ModificarResponse() {
        }
        
        public ModificarResponse(ConsumirArqui.webArticulo.ModificarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ModificarResult;
        
        public ModificarResponseBody() {
        }
        
        public ModificarResponseBody(string ModificarResult) {
            this.ModificarResult = ModificarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Eliminar", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirArqui.webArticulo.EliminarRequestBody Body;
        
        public EliminarRequest() {
        }
        
        public EliminarRequest(ConsumirArqui.webArticulo.EliminarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idArticulo;
        
        public EliminarRequestBody() {
        }
        
        public EliminarRequestBody(string idArticulo) {
            this.idArticulo = idArticulo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirArqui.webArticulo.EliminarResponseBody Body;
        
        public EliminarResponse() {
        }
        
        public EliminarResponse(ConsumirArqui.webArticulo.EliminarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EliminarResult;
        
        public EliminarResponseBody() {
        }
        
        public EliminarResponseBody(string EliminarResult) {
            this.EliminarResult = EliminarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceArquiSoapChannel : ConsumirArqui.webArticulo.ServiceArquiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceArquiSoapClient : System.ServiceModel.ClientBase<ConsumirArqui.webArticulo.ServiceArquiSoap>, ConsumirArqui.webArticulo.ServiceArquiSoap {
        
        public ServiceArquiSoapClient() {
        }
        
        public ServiceArquiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceArquiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceArquiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceArquiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirArqui.webArticulo.InsertarResponse ConsumirArqui.webArticulo.ServiceArquiSoap.Insertar(ConsumirArqui.webArticulo.InsertarRequest request) {
            return base.Channel.Insertar(request);
        }
        
        public string Insertar(string idArticulo, string nombre, string precio, string costo, string cantidad, string material, string categoria, string descripcion) {
            ConsumirArqui.webArticulo.InsertarRequest inValue = new ConsumirArqui.webArticulo.InsertarRequest();
            inValue.Body = new ConsumirArqui.webArticulo.InsertarRequestBody();
            inValue.Body.idArticulo = idArticulo;
            inValue.Body.nombre = nombre;
            inValue.Body.precio = precio;
            inValue.Body.costo = costo;
            inValue.Body.cantidad = cantidad;
            inValue.Body.material = material;
            inValue.Body.categoria = categoria;
            inValue.Body.descripcion = descripcion;
            ConsumirArqui.webArticulo.InsertarResponse retVal = ((ConsumirArqui.webArticulo.ServiceArquiSoap)(this)).Insertar(inValue);
            return retVal.Body.InsertarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirArqui.webArticulo.InsertarResponse> ConsumirArqui.webArticulo.ServiceArquiSoap.InsertarAsync(ConsumirArqui.webArticulo.InsertarRequest request) {
            return base.Channel.InsertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirArqui.webArticulo.InsertarResponse> InsertarAsync(string idArticulo, string nombre, string precio, string costo, string cantidad, string material, string categoria, string descripcion) {
            ConsumirArqui.webArticulo.InsertarRequest inValue = new ConsumirArqui.webArticulo.InsertarRequest();
            inValue.Body = new ConsumirArqui.webArticulo.InsertarRequestBody();
            inValue.Body.idArticulo = idArticulo;
            inValue.Body.nombre = nombre;
            inValue.Body.precio = precio;
            inValue.Body.costo = costo;
            inValue.Body.cantidad = cantidad;
            inValue.Body.material = material;
            inValue.Body.categoria = categoria;
            inValue.Body.descripcion = descripcion;
            return ((ConsumirArqui.webArticulo.ServiceArquiSoap)(this)).InsertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirArqui.webArticulo.ModificarResponse ConsumirArqui.webArticulo.ServiceArquiSoap.Modificar(ConsumirArqui.webArticulo.ModificarRequest request) {
            return base.Channel.Modificar(request);
        }
        
        public string Modificar(string idArticulo, string nombre, string precio, string costo, string cantidad, string material, string categoria, string descripcion) {
            ConsumirArqui.webArticulo.ModificarRequest inValue = new ConsumirArqui.webArticulo.ModificarRequest();
            inValue.Body = new ConsumirArqui.webArticulo.ModificarRequestBody();
            inValue.Body.idArticulo = idArticulo;
            inValue.Body.nombre = nombre;
            inValue.Body.precio = precio;
            inValue.Body.costo = costo;
            inValue.Body.cantidad = cantidad;
            inValue.Body.material = material;
            inValue.Body.categoria = categoria;
            inValue.Body.descripcion = descripcion;
            ConsumirArqui.webArticulo.ModificarResponse retVal = ((ConsumirArqui.webArticulo.ServiceArquiSoap)(this)).Modificar(inValue);
            return retVal.Body.ModificarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirArqui.webArticulo.ModificarResponse> ConsumirArqui.webArticulo.ServiceArquiSoap.ModificarAsync(ConsumirArqui.webArticulo.ModificarRequest request) {
            return base.Channel.ModificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirArqui.webArticulo.ModificarResponse> ModificarAsync(string idArticulo, string nombre, string precio, string costo, string cantidad, string material, string categoria, string descripcion) {
            ConsumirArqui.webArticulo.ModificarRequest inValue = new ConsumirArqui.webArticulo.ModificarRequest();
            inValue.Body = new ConsumirArqui.webArticulo.ModificarRequestBody();
            inValue.Body.idArticulo = idArticulo;
            inValue.Body.nombre = nombre;
            inValue.Body.precio = precio;
            inValue.Body.costo = costo;
            inValue.Body.cantidad = cantidad;
            inValue.Body.material = material;
            inValue.Body.categoria = categoria;
            inValue.Body.descripcion = descripcion;
            return ((ConsumirArqui.webArticulo.ServiceArquiSoap)(this)).ModificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirArqui.webArticulo.EliminarResponse ConsumirArqui.webArticulo.ServiceArquiSoap.Eliminar(ConsumirArqui.webArticulo.EliminarRequest request) {
            return base.Channel.Eliminar(request);
        }
        
        public string Eliminar(string idArticulo) {
            ConsumirArqui.webArticulo.EliminarRequest inValue = new ConsumirArqui.webArticulo.EliminarRequest();
            inValue.Body = new ConsumirArqui.webArticulo.EliminarRequestBody();
            inValue.Body.idArticulo = idArticulo;
            ConsumirArqui.webArticulo.EliminarResponse retVal = ((ConsumirArqui.webArticulo.ServiceArquiSoap)(this)).Eliminar(inValue);
            return retVal.Body.EliminarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirArqui.webArticulo.EliminarResponse> ConsumirArqui.webArticulo.ServiceArquiSoap.EliminarAsync(ConsumirArqui.webArticulo.EliminarRequest request) {
            return base.Channel.EliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirArqui.webArticulo.EliminarResponse> EliminarAsync(string idArticulo) {
            ConsumirArqui.webArticulo.EliminarRequest inValue = new ConsumirArqui.webArticulo.EliminarRequest();
            inValue.Body = new ConsumirArqui.webArticulo.EliminarRequestBody();
            inValue.Body.idArticulo = idArticulo;
            return ((ConsumirArqui.webArticulo.ServiceArquiSoap)(this)).EliminarAsync(inValue);
        }
    }
}
