//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirArqui.webEnvio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="webEnvio.DatosEnvioSoap")]
    public interface DatosEnvioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idCurp del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar", ReplyAction="*")]
        ConsumirArqui.webEnvio.InsertarResponse Insertar(ConsumirArqui.webEnvio.InsertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirArqui.webEnvio.InsertarResponse> InsertarAsync(ConsumirArqui.webEnvio.InsertarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idCurp del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificar", ReplyAction="*")]
        ConsumirArqui.webEnvio.ModificarResponse Modificar(ConsumirArqui.webEnvio.ModificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificar", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirArqui.webEnvio.ModificarResponse> ModificarAsync(ConsumirArqui.webEnvio.ModificarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idCliente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        ConsumirArqui.webEnvio.EliminarResponse Eliminar(ConsumirArqui.webEnvio.EliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirArqui.webEnvio.EliminarResponse> EliminarAsync(ConsumirArqui.webEnvio.EliminarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insertar", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirArqui.webEnvio.InsertarRequestBody Body;
        
        public InsertarRequest() {
        }
        
        public InsertarRequest(ConsumirArqui.webEnvio.InsertarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idCurp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string domicilio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string referencia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string estado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string municipio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string localidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string idCliente;
        
        public InsertarRequestBody() {
        }
        
        public InsertarRequestBody(string idCurp, string domicilio, string cp, string referencia, string estado, string municipio, string localidad, string idCliente) {
            this.idCurp = idCurp;
            this.domicilio = domicilio;
            this.cp = cp;
            this.referencia = referencia;
            this.estado = estado;
            this.municipio = municipio;
            this.localidad = localidad;
            this.idCliente = idCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirArqui.webEnvio.InsertarResponseBody Body;
        
        public InsertarResponse() {
        }
        
        public InsertarResponse(ConsumirArqui.webEnvio.InsertarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarResult;
        
        public InsertarResponseBody() {
        }
        
        public InsertarResponseBody(string InsertarResult) {
            this.InsertarResult = InsertarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Modificar", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirArqui.webEnvio.ModificarRequestBody Body;
        
        public ModificarRequest() {
        }
        
        public ModificarRequest(ConsumirArqui.webEnvio.ModificarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idCurp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string domicilio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string referencia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string estado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string municipio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string localidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string idCliente;
        
        public ModificarRequestBody() {
        }
        
        public ModificarRequestBody(string idCurp, string domicilio, string cp, string referencia, string estado, string municipio, string localidad, string idCliente) {
            this.idCurp = idCurp;
            this.domicilio = domicilio;
            this.cp = cp;
            this.referencia = referencia;
            this.estado = estado;
            this.municipio = municipio;
            this.localidad = localidad;
            this.idCliente = idCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirArqui.webEnvio.ModificarResponseBody Body;
        
        public ModificarResponse() {
        }
        
        public ModificarResponse(ConsumirArqui.webEnvio.ModificarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ModificarResult;
        
        public ModificarResponseBody() {
        }
        
        public ModificarResponseBody(string ModificarResult) {
            this.ModificarResult = ModificarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Eliminar", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirArqui.webEnvio.EliminarRequestBody Body;
        
        public EliminarRequest() {
        }
        
        public EliminarRequest(ConsumirArqui.webEnvio.EliminarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idCliente;
        
        public EliminarRequestBody() {
        }
        
        public EliminarRequestBody(string idCliente) {
            this.idCliente = idCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirArqui.webEnvio.EliminarResponseBody Body;
        
        public EliminarResponse() {
        }
        
        public EliminarResponse(ConsumirArqui.webEnvio.EliminarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EliminarResult;
        
        public EliminarResponseBody() {
        }
        
        public EliminarResponseBody(string EliminarResult) {
            this.EliminarResult = EliminarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DatosEnvioSoapChannel : ConsumirArqui.webEnvio.DatosEnvioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatosEnvioSoapClient : System.ServiceModel.ClientBase<ConsumirArqui.webEnvio.DatosEnvioSoap>, ConsumirArqui.webEnvio.DatosEnvioSoap {
        
        public DatosEnvioSoapClient() {
        }
        
        public DatosEnvioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatosEnvioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatosEnvioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatosEnvioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirArqui.webEnvio.InsertarResponse ConsumirArqui.webEnvio.DatosEnvioSoap.Insertar(ConsumirArqui.webEnvio.InsertarRequest request) {
            return base.Channel.Insertar(request);
        }
        
        public string Insertar(string idCurp, string domicilio, string cp, string referencia, string estado, string municipio, string localidad, string idCliente) {
            ConsumirArqui.webEnvio.InsertarRequest inValue = new ConsumirArqui.webEnvio.InsertarRequest();
            inValue.Body = new ConsumirArqui.webEnvio.InsertarRequestBody();
            inValue.Body.idCurp = idCurp;
            inValue.Body.domicilio = domicilio;
            inValue.Body.cp = cp;
            inValue.Body.referencia = referencia;
            inValue.Body.estado = estado;
            inValue.Body.municipio = municipio;
            inValue.Body.localidad = localidad;
            inValue.Body.idCliente = idCliente;
            ConsumirArqui.webEnvio.InsertarResponse retVal = ((ConsumirArqui.webEnvio.DatosEnvioSoap)(this)).Insertar(inValue);
            return retVal.Body.InsertarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirArqui.webEnvio.InsertarResponse> ConsumirArqui.webEnvio.DatosEnvioSoap.InsertarAsync(ConsumirArqui.webEnvio.InsertarRequest request) {
            return base.Channel.InsertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirArqui.webEnvio.InsertarResponse> InsertarAsync(string idCurp, string domicilio, string cp, string referencia, string estado, string municipio, string localidad, string idCliente) {
            ConsumirArqui.webEnvio.InsertarRequest inValue = new ConsumirArqui.webEnvio.InsertarRequest();
            inValue.Body = new ConsumirArqui.webEnvio.InsertarRequestBody();
            inValue.Body.idCurp = idCurp;
            inValue.Body.domicilio = domicilio;
            inValue.Body.cp = cp;
            inValue.Body.referencia = referencia;
            inValue.Body.estado = estado;
            inValue.Body.municipio = municipio;
            inValue.Body.localidad = localidad;
            inValue.Body.idCliente = idCliente;
            return ((ConsumirArqui.webEnvio.DatosEnvioSoap)(this)).InsertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirArqui.webEnvio.ModificarResponse ConsumirArqui.webEnvio.DatosEnvioSoap.Modificar(ConsumirArqui.webEnvio.ModificarRequest request) {
            return base.Channel.Modificar(request);
        }
        
        public string Modificar(string idCurp, string domicilio, string cp, string referencia, string estado, string municipio, string localidad, string idCliente) {
            ConsumirArqui.webEnvio.ModificarRequest inValue = new ConsumirArqui.webEnvio.ModificarRequest();
            inValue.Body = new ConsumirArqui.webEnvio.ModificarRequestBody();
            inValue.Body.idCurp = idCurp;
            inValue.Body.domicilio = domicilio;
            inValue.Body.cp = cp;
            inValue.Body.referencia = referencia;
            inValue.Body.estado = estado;
            inValue.Body.municipio = municipio;
            inValue.Body.localidad = localidad;
            inValue.Body.idCliente = idCliente;
            ConsumirArqui.webEnvio.ModificarResponse retVal = ((ConsumirArqui.webEnvio.DatosEnvioSoap)(this)).Modificar(inValue);
            return retVal.Body.ModificarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirArqui.webEnvio.ModificarResponse> ConsumirArqui.webEnvio.DatosEnvioSoap.ModificarAsync(ConsumirArqui.webEnvio.ModificarRequest request) {
            return base.Channel.ModificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirArqui.webEnvio.ModificarResponse> ModificarAsync(string idCurp, string domicilio, string cp, string referencia, string estado, string municipio, string localidad, string idCliente) {
            ConsumirArqui.webEnvio.ModificarRequest inValue = new ConsumirArqui.webEnvio.ModificarRequest();
            inValue.Body = new ConsumirArqui.webEnvio.ModificarRequestBody();
            inValue.Body.idCurp = idCurp;
            inValue.Body.domicilio = domicilio;
            inValue.Body.cp = cp;
            inValue.Body.referencia = referencia;
            inValue.Body.estado = estado;
            inValue.Body.municipio = municipio;
            inValue.Body.localidad = localidad;
            inValue.Body.idCliente = idCliente;
            return ((ConsumirArqui.webEnvio.DatosEnvioSoap)(this)).ModificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirArqui.webEnvio.EliminarResponse ConsumirArqui.webEnvio.DatosEnvioSoap.Eliminar(ConsumirArqui.webEnvio.EliminarRequest request) {
            return base.Channel.Eliminar(request);
        }
        
        public string Eliminar(string idCliente) {
            ConsumirArqui.webEnvio.EliminarRequest inValue = new ConsumirArqui.webEnvio.EliminarRequest();
            inValue.Body = new ConsumirArqui.webEnvio.EliminarRequestBody();
            inValue.Body.idCliente = idCliente;
            ConsumirArqui.webEnvio.EliminarResponse retVal = ((ConsumirArqui.webEnvio.DatosEnvioSoap)(this)).Eliminar(inValue);
            return retVal.Body.EliminarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirArqui.webEnvio.EliminarResponse> ConsumirArqui.webEnvio.DatosEnvioSoap.EliminarAsync(ConsumirArqui.webEnvio.EliminarRequest request) {
            return base.Channel.EliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirArqui.webEnvio.EliminarResponse> EliminarAsync(string idCliente) {
            ConsumirArqui.webEnvio.EliminarRequest inValue = new ConsumirArqui.webEnvio.EliminarRequest();
            inValue.Body = new ConsumirArqui.webEnvio.EliminarRequestBody();
            inValue.Body.idCliente = idCliente;
            return ((ConsumirArqui.webEnvio.DatosEnvioSoap)(this)).EliminarAsync(inValue);
        }
    }
}
