//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirArqui.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceArticuloPedidoSoap")]
    public interface ServiceArticuloPedidoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idArticulo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar", ReplyAction="*")]
        ConsumirArqui.ServiceReference1.InsertarResponse Insertar(ConsumirArqui.ServiceReference1.InsertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirArqui.ServiceReference1.InsertarResponse> InsertarAsync(ConsumirArqui.ServiceReference1.InsertarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idArticulo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificar", ReplyAction="*")]
        ConsumirArqui.ServiceReference1.ModificarResponse Modificar(ConsumirArqui.ServiceReference1.ModificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificar", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirArqui.ServiceReference1.ModificarResponse> ModificarAsync(ConsumirArqui.ServiceReference1.ModificarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idCurp del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        ConsumirArqui.ServiceReference1.EliminarResponse Eliminar(ConsumirArqui.ServiceReference1.EliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirArqui.ServiceReference1.EliminarResponse> EliminarAsync(ConsumirArqui.ServiceReference1.EliminarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insertar", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirArqui.ServiceReference1.InsertarRequestBody Body;
        
        public InsertarRequest() {
        }
        
        public InsertarRequest(ConsumirArqui.ServiceReference1.InsertarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idArticulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idCurp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cantidad;
        
        public InsertarRequestBody() {
        }
        
        public InsertarRequestBody(string idArticulo, string idCurp, string cantidad) {
            this.idArticulo = idArticulo;
            this.idCurp = idCurp;
            this.cantidad = cantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirArqui.ServiceReference1.InsertarResponseBody Body;
        
        public InsertarResponse() {
        }
        
        public InsertarResponse(ConsumirArqui.ServiceReference1.InsertarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarResult;
        
        public InsertarResponseBody() {
        }
        
        public InsertarResponseBody(string InsertarResult) {
            this.InsertarResult = InsertarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Modificar", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirArqui.ServiceReference1.ModificarRequestBody Body;
        
        public ModificarRequest() {
        }
        
        public ModificarRequest(ConsumirArqui.ServiceReference1.ModificarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idArticulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idCurp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cantidad;
        
        public ModificarRequestBody() {
        }
        
        public ModificarRequestBody(string idArticulo, string idCurp, string cantidad) {
            this.idArticulo = idArticulo;
            this.idCurp = idCurp;
            this.cantidad = cantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirArqui.ServiceReference1.ModificarResponseBody Body;
        
        public ModificarResponse() {
        }
        
        public ModificarResponse(ConsumirArqui.ServiceReference1.ModificarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ModificarResult;
        
        public ModificarResponseBody() {
        }
        
        public ModificarResponseBody(string ModificarResult) {
            this.ModificarResult = ModificarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Eliminar", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirArqui.ServiceReference1.EliminarRequestBody Body;
        
        public EliminarRequest() {
        }
        
        public EliminarRequest(ConsumirArqui.ServiceReference1.EliminarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idCurp;
        
        public EliminarRequestBody() {
        }
        
        public EliminarRequestBody(string idCurp) {
            this.idCurp = idCurp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirArqui.ServiceReference1.EliminarResponseBody Body;
        
        public EliminarResponse() {
        }
        
        public EliminarResponse(ConsumirArqui.ServiceReference1.EliminarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EliminarResult;
        
        public EliminarResponseBody() {
        }
        
        public EliminarResponseBody(string EliminarResult) {
            this.EliminarResult = EliminarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceArticuloPedidoSoapChannel : ConsumirArqui.ServiceReference1.ServiceArticuloPedidoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceArticuloPedidoSoapClient : System.ServiceModel.ClientBase<ConsumirArqui.ServiceReference1.ServiceArticuloPedidoSoap>, ConsumirArqui.ServiceReference1.ServiceArticuloPedidoSoap {
        
        public ServiceArticuloPedidoSoapClient() {
        }
        
        public ServiceArticuloPedidoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceArticuloPedidoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceArticuloPedidoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceArticuloPedidoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirArqui.ServiceReference1.InsertarResponse ConsumirArqui.ServiceReference1.ServiceArticuloPedidoSoap.Insertar(ConsumirArqui.ServiceReference1.InsertarRequest request) {
            return base.Channel.Insertar(request);
        }
        
        public string Insertar(string idArticulo, string idCurp, string cantidad) {
            ConsumirArqui.ServiceReference1.InsertarRequest inValue = new ConsumirArqui.ServiceReference1.InsertarRequest();
            inValue.Body = new ConsumirArqui.ServiceReference1.InsertarRequestBody();
            inValue.Body.idArticulo = idArticulo;
            inValue.Body.idCurp = idCurp;
            inValue.Body.cantidad = cantidad;
            ConsumirArqui.ServiceReference1.InsertarResponse retVal = ((ConsumirArqui.ServiceReference1.ServiceArticuloPedidoSoap)(this)).Insertar(inValue);
            return retVal.Body.InsertarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirArqui.ServiceReference1.InsertarResponse> ConsumirArqui.ServiceReference1.ServiceArticuloPedidoSoap.InsertarAsync(ConsumirArqui.ServiceReference1.InsertarRequest request) {
            return base.Channel.InsertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirArqui.ServiceReference1.InsertarResponse> InsertarAsync(string idArticulo, string idCurp, string cantidad) {
            ConsumirArqui.ServiceReference1.InsertarRequest inValue = new ConsumirArqui.ServiceReference1.InsertarRequest();
            inValue.Body = new ConsumirArqui.ServiceReference1.InsertarRequestBody();
            inValue.Body.idArticulo = idArticulo;
            inValue.Body.idCurp = idCurp;
            inValue.Body.cantidad = cantidad;
            return ((ConsumirArqui.ServiceReference1.ServiceArticuloPedidoSoap)(this)).InsertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirArqui.ServiceReference1.ModificarResponse ConsumirArqui.ServiceReference1.ServiceArticuloPedidoSoap.Modificar(ConsumirArqui.ServiceReference1.ModificarRequest request) {
            return base.Channel.Modificar(request);
        }
        
        public string Modificar(string idArticulo, string idCurp, string cantidad) {
            ConsumirArqui.ServiceReference1.ModificarRequest inValue = new ConsumirArqui.ServiceReference1.ModificarRequest();
            inValue.Body = new ConsumirArqui.ServiceReference1.ModificarRequestBody();
            inValue.Body.idArticulo = idArticulo;
            inValue.Body.idCurp = idCurp;
            inValue.Body.cantidad = cantidad;
            ConsumirArqui.ServiceReference1.ModificarResponse retVal = ((ConsumirArqui.ServiceReference1.ServiceArticuloPedidoSoap)(this)).Modificar(inValue);
            return retVal.Body.ModificarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirArqui.ServiceReference1.ModificarResponse> ConsumirArqui.ServiceReference1.ServiceArticuloPedidoSoap.ModificarAsync(ConsumirArqui.ServiceReference1.ModificarRequest request) {
            return base.Channel.ModificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirArqui.ServiceReference1.ModificarResponse> ModificarAsync(string idArticulo, string idCurp, string cantidad) {
            ConsumirArqui.ServiceReference1.ModificarRequest inValue = new ConsumirArqui.ServiceReference1.ModificarRequest();
            inValue.Body = new ConsumirArqui.ServiceReference1.ModificarRequestBody();
            inValue.Body.idArticulo = idArticulo;
            inValue.Body.idCurp = idCurp;
            inValue.Body.cantidad = cantidad;
            return ((ConsumirArqui.ServiceReference1.ServiceArticuloPedidoSoap)(this)).ModificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirArqui.ServiceReference1.EliminarResponse ConsumirArqui.ServiceReference1.ServiceArticuloPedidoSoap.Eliminar(ConsumirArqui.ServiceReference1.EliminarRequest request) {
            return base.Channel.Eliminar(request);
        }
        
        public string Eliminar(string idCurp) {
            ConsumirArqui.ServiceReference1.EliminarRequest inValue = new ConsumirArqui.ServiceReference1.EliminarRequest();
            inValue.Body = new ConsumirArqui.ServiceReference1.EliminarRequestBody();
            inValue.Body.idCurp = idCurp;
            ConsumirArqui.ServiceReference1.EliminarResponse retVal = ((ConsumirArqui.ServiceReference1.ServiceArticuloPedidoSoap)(this)).Eliminar(inValue);
            return retVal.Body.EliminarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirArqui.ServiceReference1.EliminarResponse> ConsumirArqui.ServiceReference1.ServiceArticuloPedidoSoap.EliminarAsync(ConsumirArqui.ServiceReference1.EliminarRequest request) {
            return base.Channel.EliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirArqui.ServiceReference1.EliminarResponse> EliminarAsync(string idCurp) {
            ConsumirArqui.ServiceReference1.EliminarRequest inValue = new ConsumirArqui.ServiceReference1.EliminarRequest();
            inValue.Body = new ConsumirArqui.ServiceReference1.EliminarRequestBody();
            inValue.Body.idCurp = idCurp;
            return ((ConsumirArqui.ServiceReference1.ServiceArticuloPedidoSoap)(this)).EliminarAsync(inValue);
        }
    }
}
